version: '3.9'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../app:/app
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
    depends_on:
      - mongodb
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - app_network

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

volumes:
  mongodb_data:

networks:
  app_network:
    driver: bridge
